_target_: contrib.eeg.models_directinv.HeckerLSTMpl
n_electrodes: ${dataset.n_electrodes}
hidden_size: 85 
n_sources: ${dataset.n_sources}
optimizer: ${optimizer}
lr: 0.001
criterion: 
  _tagert_: contrib.eeg.model_short.CosineReshape 