# Shape of the data
n_times: 64
n_sources: 1284 
n_electrodes: 90

# Head model 
subject_name: 'fsaverage'
orientation: 'constrained'
electrode_montage: 'standard_1020'
source_sampling: 'ico3'

# Simulation
simu_name: ses_125ms_test
snr_db: 5
noise_type: {"white":1.}
scaler_type: 'linear'
replace_root: True

to_load: 2000
