n_times: 64
n_sources: 1283 
n_electrodes: 59

#head model 
subject_name: 'sample'
orientation: 'constrained'
electrode_montage: 'sample'
source_sampling: 'ico3-fsav-morph'

# simulation
# simu_name: '_dl_ses_fsaverage_st1020_'
simu_name: 'ses_125ms_morph_sample2_test'
snr_db: 5
noise_type: {"white":1.}
replace_root: True

to_load: 2000