_target_: contrib.eeg.models.ConvAEPrior
dim_in: ${dataset.n_sources}
dim_hidden: 128
dim_out: ${dataset.n_sources}
kernel_size: 3
pretrained_model_path: null #pretrained_priors/pretrained_ae_cosine_ico3.ckpt
fixed: false
cost_fn: ${cost_functions.prior_cost_fn}